[package]
name = "advent2018"
version = "0.1.0"
authors = ["stijnh <mail@stijnh.nl>"]
edition = "2018"

[profile.release]
lto = true
panic = "abort"
opt-level = 3

[dependencies]
regex = "1.1.0"
ndarray = "0.12.1"
itertools = "0.8.0"
image = "0.20.1"
binary-heap-plus = "0.1.4"
enumset = "0.3.14"
